// Mocks generated by Mockito 5.3.0 from annotations
// in economy_sim/test/engine/game_field_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:economy_sim/engine/game_cell.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GameCell].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameCell extends _i1.Mock implements _i2.GameCell {
  MockGameCell() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void queueTransaction(String? material, int? quantity) => super.noSuchMethod(
      Invocation.method(#queueTransaction, [material, quantity]),
      returnValueForMissingStub: null);
  @override
  void commitPendingTransactions() =>
      super.noSuchMethod(Invocation.method(#commitPendingTransactions, []),
          returnValueForMissingStub: null);
  @override
  int getInventoryQuantity(String? material) =>
      (super.noSuchMethod(Invocation.method(#getInventoryQuantity, [material]),
          returnValue: 0) as int);
  @override
  void executeCurrentRecipe() =>
      super.noSuchMethod(Invocation.method(#executeCurrentRecipe, []),
          returnValueForMissingStub: null);
  @override
  void conductInventoryToNeighbors(List<_i2.GameCell>? neighbors) =>
      super.noSuchMethod(
          Invocation.method(#conductInventoryToNeighbors, [neighbors]),
          returnValueForMissingStub: null);
}
